# SwiftLint Configuration for IntervalPro
# Following CLAUDE.md style guidelines

# Enabled rules
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled rules - per CLAUDE.md
disabled_rules:
  - trailing_whitespace  # Sometimes conflicts with formatting
  - todo  # We use TODO comments during development

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - hr
    - bpm
    - i
    - j
    - to
    - db

# CLAUDE.md: Never use force unwrap
force_unwrapping:
  severity: error

force_cast:
  severity: error

force_try:
  severity: error

# CLAUDE.md: Never use print() - use os.Logger
custom_rules:
  no_print_statements:
    name: "No print statements"
    regex: "\\bprint\\s*\\("
    message: "Use os.Logger instead of print(). See CLAUDE.md."
    severity: warning
    match_kinds:
      - identifier

  no_uikit_import:
    name: "No UIKit imports"
    regex: "^import UIKit$"
    message: "UIKit is prohibited. Use SwiftUI only. See CLAUDE.md."
    severity: error
    excluded:
      - "IntervalPro/Core/Audio/.*"  # Music SDKs require UIKit

  no_hardcoded_bpm:
    name: "No hardcoded BPM values"
    regex: "(?:heartRate|hr|bpm)\\s*[><=!]+\\s*\\d{2,3}[^0-9]"
    message: "Do not hardcode BPM values. Use HeartRateZone configuration. See CLAUDE.md."
    severity: warning

# Paths
included:
  - IntervalPro

excluded:
  - IntervalPro/Resources
  - Tests
  - .build
  - Pods
  - Packages

# Reporter
reporter: "xcode"
