import CoreData
import Foundation

/// Core Data entity wrapper for TrainingPlan
/// Note: The actual NSManagedObject subclass is generated by Xcode from the .xcdatamodeld
/// This file provides mapping between the entity and the domain model

extension TrainingPlanEntity {
    /// Convert Core Data entity to domain model
    func toDomainModel() -> TrainingPlan? {
        guard let id = id,
              let name = name else {
            return nil
        }

        return TrainingPlan(
            id: id,
            name: name,
            workZone: HeartRateZone(
                targetBPM: Int(workTargetBPM),
                toleranceBPM: Int(workToleranceBPM)
            ),
            restZone: HeartRateZone(
                targetBPM: Int(restTargetBPM),
                toleranceBPM: Int(restToleranceBPM)
            ),
            workDuration: workDuration,
            restDuration: restDuration,
            seriesCount: Int(seriesCount),
            warmupDuration: warmupDuration > 0 ? warmupDuration : nil,
            cooldownDuration: cooldownDuration > 0 ? cooldownDuration : nil,
            createdAt: createdAt ?? Date(),
            isDefault: isDefault
        )
    }

    /// Update entity from domain model
    func update(from plan: TrainingPlan) {
        self.id = plan.id
        self.name = plan.name
        self.workTargetBPM = Int16(plan.workZone.targetBPM)
        self.workToleranceBPM = Int16(plan.workZone.toleranceBPM)
        self.restTargetBPM = Int16(plan.restZone.targetBPM)
        self.restToleranceBPM = Int16(plan.restZone.toleranceBPM)
        self.workDuration = plan.workDuration
        self.restDuration = plan.restDuration
        self.seriesCount = Int16(plan.seriesCount)
        self.warmupDuration = plan.warmupDuration ?? 0
        self.cooldownDuration = plan.cooldownDuration ?? 0
        self.createdAt = plan.createdAt
        self.isDefault = plan.isDefault
    }
}

// MARK: - Fetch Requests
extension TrainingPlanEntity {
    static func fetchRequest() -> NSFetchRequest<TrainingPlanEntity> {
        NSFetchRequest<TrainingPlanEntity>(entityName: "TrainingPlanEntity")
    }

    static func fetchByID(_ id: UUID) -> NSFetchRequest<TrainingPlanEntity> {
        let request = fetchRequest()
        request.predicate = NSPredicate(format: "id == %@", id as CVarArg)
        request.fetchLimit = 1
        return request
    }

    static func fetchAllSorted() -> NSFetchRequest<TrainingPlanEntity> {
        let request = fetchRequest()
        request.sortDescriptors = [
            NSSortDescriptor(keyPath: \TrainingPlanEntity.isDefault, ascending: false),
            NSSortDescriptor(keyPath: \TrainingPlanEntity.createdAt, ascending: false)
        ]
        return request
    }

    static func fetchCustomPlans() -> NSFetchRequest<TrainingPlanEntity> {
        let request = fetchRequest()
        request.predicate = NSPredicate(format: "isDefault == NO")
        request.sortDescriptors = [
            NSSortDescriptor(keyPath: \TrainingPlanEntity.createdAt, ascending: false)
        ]
        return request
    }
}

// MARK: - Placeholder for Code Generation
/// This class is a placeholder. The actual class will be generated by Xcode
/// from the .xcdatamodeld file. Attributes:
/// - id: UUID
/// - name: String
/// - workTargetBPM: Int16
/// - workToleranceBPM: Int16
/// - restTargetBPM: Int16
/// - restToleranceBPM: Int16
/// - workDuration: Double
/// - restDuration: Double
/// - seriesCount: Int16
/// - warmupDuration: Double
/// - cooldownDuration: Double
/// - createdAt: Date
/// - isDefault: Bool
@objc(TrainingPlanEntity)
public class TrainingPlanEntity: NSManagedObject {
    @NSManaged public var id: UUID?
    @NSManaged public var name: String?
    @NSManaged public var workTargetBPM: Int16
    @NSManaged public var workToleranceBPM: Int16
    @NSManaged public var restTargetBPM: Int16
    @NSManaged public var restToleranceBPM: Int16
    @NSManaged public var workDuration: Double
    @NSManaged public var restDuration: Double
    @NSManaged public var seriesCount: Int16
    @NSManaged public var warmupDuration: Double
    @NSManaged public var cooldownDuration: Double
    @NSManaged public var createdAt: Date?
    @NSManaged public var isDefault: Bool
    @NSManaged public var sessions: NSSet?
}
